# Control
xDes: [4, 0, 3.141592653589793, 0]

# PID
Kp: 150
Ki: 3
Kd: 50

# Pole Placement
poles: [-1, -2, -3, -4]

# LQR
R: .01
Q: [100, 5, 1, 1]


# Dynamics
l: 2
mb: 1
mw: 5
Iw: .2
Ib: .5
r: .25
d: 1

# Animation
style: cart
width: 0.4
height: 1.25